obj-$(CONFIG_MTK_RTC) := mtk_rtc.o

# LGE_CHANGE_S : 2014-02-18 yeonsoo7.kim@lge.com, LG Secure Clock
obj-$(CONFIG_RTC_INTF_SECCLK) += secclk.o
# LGE_CHANGE_E : 2014-02-18 yeonsoo7.kim@lge.com, LG Secure Clock
